version: '3.1'

services:
  api-db:
    image: postgres
    environment:
      POSTGRES_DB: apidb
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pwd1234
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api-pgadmin:
    image: adminer
    ports:
      - 8080:8080